# Generated by Django 5.0.2 on 2025-06-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={},
        ),
    ]
