# Generated by Django 5.0.2 on 2025-06-12 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, error_messages={'required': 'Username is required.', 'unique': 'A user with that username already exists.'}, max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$'), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(150)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the user account was created.'),
        ),
    ]
